/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.TodoApp.PedroGomes.view;

import com.TodoApp.PedroGomes.controller.TaskController;
import com.TodoApp.PedroGomes.model.Project;
import com.TodoApp.PedroGomes.model.Task;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class EditTaskDialogScreen extends javax.swing.JDialog {

    TaskController controller;
    Project project;
    
    public EditTaskDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        hideErrorFields();
        
        controller = new TaskController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TaskSubmitButton = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        NameInput = new javax.swing.JTextField();
        DescriptionLabel = new javax.swing.JLabel();
        DescriptionInput = new javax.swing.JTextField();
        DeadlineLabel = new javax.swing.JLabel();
        DeadlineInput = new javax.swing.JFormattedTextField();
        ObservationsLabel = new javax.swing.JLabel();
        ObservationsInput = new javax.swing.JTextField();
        NameRequiredError = new javax.swing.JLabel();
        DeadlineRequiredError = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Description");
        jLabel6.setMaximumSize(new java.awt.Dimension(34, 13));
        jLabel6.setMinimumSize(new java.awt.Dimension(34, 13));
        jLabel6.setPreferredSize(new java.awt.Dimension(34, 13));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        jTextField3.setToolTipText("Type the description of the project");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));

        Header.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Task");

        TaskSubmitButton.setBackground(new java.awt.Color(0, 153, 102));
        TaskSubmitButton.setForeground(new java.awt.Color(0, 153, 102));
        TaskSubmitButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskSubmitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/check.png"))); // NOI18N
        TaskSubmitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaskSubmitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskSubmitButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TaskSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskSubmitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Body.setBackground(new java.awt.Color(255, 255, 255));

        NameLabel.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 0, 0));
        NameLabel.setText("Name");

        NameInput.setBackground(new java.awt.Color(255, 255, 255));
        NameInput.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        NameInput.setForeground(new java.awt.Color(0, 0, 0));
        NameInput.setToolTipText("Type the name of the project");
        NameInput.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        NameInput.setSelectionColor(new java.awt.Color(0, 152, 102));
        NameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameInputActionPerformed(evt);
            }
        });

        DescriptionLabel.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        DescriptionLabel.setForeground(new java.awt.Color(0, 0, 0));
        DescriptionLabel.setText("Description");
        DescriptionLabel.setMaximumSize(new java.awt.Dimension(34, 13));
        DescriptionLabel.setMinimumSize(new java.awt.Dimension(34, 13));
        DescriptionLabel.setPreferredSize(new java.awt.Dimension(34, 13));

        DescriptionInput.setBackground(new java.awt.Color(255, 255, 255));
        DescriptionInput.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        DescriptionInput.setForeground(new java.awt.Color(0, 0, 0));
        DescriptionInput.setToolTipText("Type the description of the project");
        DescriptionInput.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        DescriptionInput.setSelectionColor(new java.awt.Color(0, 152, 102));

        DeadlineLabel.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        DeadlineLabel.setForeground(new java.awt.Color(0, 0, 0));
        DeadlineLabel.setText("Deadline");
        DeadlineLabel.setMaximumSize(new java.awt.Dimension(34, 13));
        DeadlineLabel.setMinimumSize(new java.awt.Dimension(34, 13));
        DeadlineLabel.setPreferredSize(new java.awt.Dimension(34, 13));

        DeadlineInput.setBackground(new java.awt.Color(255, 255, 255));
        DeadlineInput.setForeground(new java.awt.Color(0, 0, 0));
        DeadlineInput.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        DeadlineInput.setToolTipText("Date of the deadline");
        DeadlineInput.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        DeadlineInput.setSelectionColor(new java.awt.Color(0, 152, 102));
        DeadlineInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeadlineInputActionPerformed(evt);
            }
        });

        ObservationsLabel.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        ObservationsLabel.setForeground(new java.awt.Color(0, 0, 0));
        ObservationsLabel.setText("Notes");

        ObservationsInput.setBackground(new java.awt.Color(255, 255, 255));
        ObservationsInput.setFont(new java.awt.Font("Helvetica", 0, 13)); // NOI18N
        ObservationsInput.setForeground(new java.awt.Color(0, 0, 0));
        ObservationsInput.setToolTipText("Type the description of the project");
        ObservationsInput.setSelectedTextColor(new java.awt.Color(255, 255, 255));
        ObservationsInput.setSelectionColor(new java.awt.Color(0, 152, 102));
        ObservationsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObservationsInputActionPerformed(evt);
            }
        });

        NameRequiredError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameRequiredError.setForeground(new java.awt.Color(204, 51, 0));
        NameRequiredError.setText("Required");

        DeadlineRequiredError.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DeadlineRequiredError.setForeground(new java.awt.Color(204, 51, 0));
        DeadlineRequiredError.setText("Required");

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameRequiredError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DescriptionInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NameInput)
                    .addComponent(DeadlineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeadlineInput)
                    .addComponent(ObservationsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ObservationsInput, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(DescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeadlineRequiredError, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameRequiredError, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(DescriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeadlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeadlineInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DeadlineRequiredError, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObservationsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ObservationsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameInputActionPerformed

    private void DeadlineInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeadlineInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeadlineInputActionPerformed

    private void ObservationsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObservationsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ObservationsInputActionPerformed

    private void TaskSubmitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskSubmitButtonMouseClicked
        try {
            if(areFieldsValid()) {
                Task task = new Task();
            
                task.setProjectId(project.getId());
                System.out.println(project.getClass());
                task.setName(NameInput.getText());
                task.setDescription(DescriptionInput.getText());
                task.setObservations(ObservationsInput.getText());
            
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                Date deadline = dateFormat.parse(DeadlineInput.getText());           
                task.setDeadline(deadline);
              
                
                this.dispose();
            } else {
                hideErrorFields();
                
                if(NameInput.getText().isEmpty()) {
                    NameRequiredError.setVisible(true);
                }
                
                if(DeadlineInput.getText().isEmpty()) {
                    DeadlineRequiredError.setVisible(true);
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_TaskSubmitButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTaskDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditTaskDialogScreen dialog = new EditTaskDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JFormattedTextField DeadlineInput;
    private javax.swing.JLabel DeadlineLabel;
    private javax.swing.JLabel DeadlineRequiredError;
    private javax.swing.JTextField DescriptionInput;
    private javax.swing.JLabel DescriptionLabel;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField NameInput;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel NameRequiredError;
    private javax.swing.JTextField ObservationsInput;
    private javax.swing.JLabel ObservationsLabel;
    private javax.swing.JLabel TaskSubmitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project = project;
    }
    
    public void hideErrorFields() {
        NameRequiredError.setVisible(false);
        DeadlineRequiredError.setVisible(false);
    }
    
    public boolean areFieldsValid() {
        return !NameInput.getText().isEmpty() && !DeadlineInput.getText().isEmpty();
    }
    
}
