/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.TodoApp.PedroGomes.view;


import com.TodoApp.PedroGomes.controller.ProjectController;
import com.TodoApp.PedroGomes.controller.TaskController;
import com.TodoApp.PedroGomes.model.Project;
import com.TodoApp.PedroGomes.model.Task;
import com.TodoApp.PedroGomes.util.ButtonColumnCellRenderer;
import com.TodoApp.PedroGomes.util.DeadlineCellRenderer;
import com.TodoApp.PedroGomes.util.TaskTableModel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
    
    DefaultListModel projectsModel;
    TaskTableModel tasksModel;

    
    
    
    public MainScreen() {
        initComponents();
        
        initDataController();
        initComponentsModel();
        
        decorationTaskTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableTasksScrool = new javax.swing.JScrollPane();
        TableTasks = new javax.swing.JTable();
        Window = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        TextLogo = new javax.swing.JLabel();
        LogoIcon = new javax.swing.JLabel();
        LogoSubttitle = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        ProjectsPanel = new javax.swing.JPanel();
        ProjectsTitle = new javax.swing.JLabel();
        ProjectButton = new javax.swing.JLabel();
        TaskPanel = new javax.swing.JPanel();
        TaskTitle = new javax.swing.JLabel();
        TaskButton = new javax.swing.JLabel();
        ProjectsListWrapper = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProjectList = new javax.swing.JList<>();
        TaskListPanel = new javax.swing.JPanel();
        EmptyTask = new javax.swing.JPanel();
        EmptyListIcon = new javax.swing.JLabel();
        EmptyListTitle = new javax.swing.JLabel();
        EmptyListSubtitile = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        TableTasksScrool.setBackground(new java.awt.Color(255, 255, 255));
        TableTasksScrool.setForeground(new java.awt.Color(255, 255, 255));

        TableTasks.setBackground(new java.awt.Color(255, 255, 255));
        TableTasks.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TableTasks.setForeground(new java.awt.Color(0, 0, 0));
        TableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Description", "Deadline", "Task Completed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableTasks.setToolTipText("");
        TableTasks.setAutoscrolls(false);
        TableTasks.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TableTasks.setGridColor(new java.awt.Color(255, 255, 255));
        TableTasks.setRequestFocusEnabled(false);
        TableTasks.setRowHeight(48);
        TableTasks.setSelectionBackground(new java.awt.Color(0, 238, 125));
        TableTasks.setSelectionForeground(new java.awt.Color(0, 0, 0));
        TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TableTasks.setShowGrid(false);
        TableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableTasksMouseClicked(evt);
            }
        });
        TableTasksScrool.setViewportView(TableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Window.setBackground(new java.awt.Color(204, 204, 204));

        Header.setBackground(new java.awt.Color(0, 153, 102));
        Header.setForeground(new java.awt.Color(0, 153, 152));

        TextLogo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        TextLogo.setForeground(new java.awt.Color(255, 255, 255));
        TextLogo.setText("Todo App");

        LogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N

        LogoSubttitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LogoSubttitle.setForeground(new java.awt.Color(204, 204, 204));
        LogoSubttitle.setText("Make notes and don't forget anything.");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(LogoIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(99, 99, 99))
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(LogoSubttitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LogoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoSubttitle)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        Body.setBackground(new java.awt.Color(204, 204, 204));

        ProjectsPanel.setBackground(new java.awt.Color(255, 255, 255));
        ProjectsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProjectsTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ProjectsTitle.setForeground(new java.awt.Color(0, 153, 102));
        ProjectsTitle.setText("Projects");

        ProjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        ProjectButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProjectButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ProjectsPanelLayout = new javax.swing.GroupLayout(ProjectsPanel);
        ProjectsPanel.setLayout(ProjectsPanelLayout);
        ProjectsPanelLayout.setHorizontalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ProjectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ProjectsPanelLayout.setVerticalGroup(
            ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ProjectsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProjectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        TaskPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        TaskTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TaskTitle.setForeground(new java.awt.Color(0, 153, 102));
        TaskTitle.setText("Tasks");

        TaskButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        TaskButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TaskButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaskButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TaskPanelLayout = new javax.swing.GroupLayout(TaskPanel);
        TaskPanel.setLayout(TaskPanelLayout);
        TaskPanelLayout.setHorizontalGroup(
            TaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TaskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TaskButton)
                .addContainerGap())
        );
        TaskPanelLayout.setVerticalGroup(
            TaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TaskPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TaskPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TaskButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(TaskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        ProjectsListWrapper.setBackground(new java.awt.Color(255, 255, 255));
        ProjectsListWrapper.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ProjectList.setBackground(new java.awt.Color(255, 255, 255));
        ProjectList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ProjectList.setForeground(new java.awt.Color(0, 0, 0));
        ProjectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProjectList.setFixedCellHeight(32);
        ProjectList.setSelectionBackground(new java.awt.Color(0, 153, 102));
        ProjectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProjectListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProjectList);

        javax.swing.GroupLayout ProjectsListWrapperLayout = new javax.swing.GroupLayout(ProjectsListWrapper);
        ProjectsListWrapper.setLayout(ProjectsListWrapperLayout);
        ProjectsListWrapperLayout.setHorizontalGroup(
            ProjectsListWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        ProjectsListWrapperLayout.setVerticalGroup(
            ProjectsListWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        TaskListPanel.setBackground(new java.awt.Color(255, 255, 255));
        TaskListPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TaskListPanel.setLayout(new javax.swing.BoxLayout(TaskListPanel, javax.swing.BoxLayout.LINE_AXIS));

        EmptyTask.setBackground(new java.awt.Color(255, 255, 255));
        EmptyTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        EmptyListIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        EmptyListTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EmptyListTitle.setForeground(new java.awt.Color(0, 153, 102));
        EmptyListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyListTitle.setText("No tasks in here :D");

        EmptyListSubtitile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EmptyListSubtitile.setForeground(new java.awt.Color(102, 102, 102));
        EmptyListSubtitile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmptyListSubtitile.setText("Click on the plus button to add a new task");

        jPanel6.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        jPanel7.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout EmptyTaskLayout = new javax.swing.GroupLayout(EmptyTask);
        EmptyTask.setLayout(EmptyTaskLayout);
        EmptyTaskLayout.setHorizontalGroup(
            EmptyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
            .addGroup(EmptyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmptyTaskLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(EmptyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmptyListSubtitile, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                        .addComponent(EmptyListTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EmptyListIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        EmptyTaskLayout.setVerticalGroup(
            EmptyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
            .addGroup(EmptyTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmptyTaskLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(EmptyListIcon)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(EmptyListTitle)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(EmptyListSubtitile)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        TaskListPanel.add(EmptyTask);

        javax.swing.GroupLayout BodyLayout = new javax.swing.GroupLayout(Body);
        Body.setLayout(BodyLayout);
        BodyLayout.setHorizontalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProjectsListWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaskListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        BodyLayout.setVerticalGroup(
            BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyLayout.createSequentialGroup()
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TaskPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProjectsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectsListWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaskListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout WindowLayout = new javax.swing.GroupLayout(Window);
        Window.setLayout(WindowLayout);
        WindowLayout.setHorizontalGroup(
            WindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        WindowLayout.setVerticalGroup(
            WindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WindowLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Window, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProjectButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectButtonMouseClicked
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                loadProjects();
            }
        });
    }//GEN-LAST:event_ProjectButtonMouseClicked

    private void TaskButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaskButtonMouseClicked
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        
        int projectIndex = ProjectList.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        
        taskDialogScreen.setVisible(true);
        
        taskDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                loadTasks(project.getId());
            }
        });
    }//GEN-LAST:event_TaskButtonMouseClicked

    private void TableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableTasksMouseClicked
        int row = TableTasks.rowAtPoint(evt.getPoint());
        int col = TableTasks.columnAtPoint(evt.getPoint());
        
        Task task = tasksModel.getTasks().get(row);
        
        switch(col) {
            case 3:        
                taskController.update(task);
                break;
            case 4: 
                TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
                
                break;
            case 5: 
                taskController.removeById(task.getId());
                tasksModel.getTasks().remove(task);
                loadTasks(task.getProjectId());
                break;
        }
    }//GEN-LAST:event_TableTasksMouseClicked

    private void ProjectListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProjectListMouseClicked
        int projectIndex = ProjectList.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        loadTasks(project.getId());
    }//GEN-LAST:event_ProjectListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body;
    private javax.swing.JLabel EmptyListIcon;
    private javax.swing.JLabel EmptyListSubtitile;
    private javax.swing.JLabel EmptyListTitle;
    private javax.swing.JPanel EmptyTask;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LogoIcon;
    private javax.swing.JLabel LogoSubttitle;
    private javax.swing.JLabel ProjectButton;
    private javax.swing.JList<String> ProjectList;
    private javax.swing.JPanel ProjectsListWrapper;
    private javax.swing.JPanel ProjectsPanel;
    private javax.swing.JLabel ProjectsTitle;
    private javax.swing.JTable TableTasks;
    private javax.swing.JScrollPane TableTasksScrool;
    private javax.swing.JLabel TaskButton;
    private javax.swing.JPanel TaskListPanel;
    private javax.swing.JPanel TaskPanel;
    private javax.swing.JLabel TaskTitle;
    private javax.swing.JLabel TextLogo;
    private javax.swing.JPanel Window;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void decorationTaskTable() {
        TableTasks.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
        TableTasks.getTableHeader().setBackground(new Color(0,153,102));
        TableTasks.getTableHeader().setForeground(new Color(255,255,255));
        
        // Deadline date
        TableTasks.getColumnModel().getColumn(2).setCellRenderer(new DeadlineCellRenderer());
        
        // Buttons
        TableTasks.getColumnModel().getColumn(4).setCellRenderer(new ButtonColumnCellRenderer("edit"));
        TableTasks.getColumnModel().getColumn(5).setCellRenderer(new ButtonColumnCellRenderer("delete"));
        
        TableTasks.setAutoCreateRowSorter(true);
    }
    
    private void initDataController() {
        projectController = new ProjectController();
        taskController = new TaskController();
    }
    
    private void initComponentsModel() {
        projectsModel = new DefaultListModel();
        loadProjects();
        
        tasksModel = new TaskTableModel();
        TableTasks.setModel(tasksModel);
        
        if(!projectsModel.isEmpty()) {
            ProjectList.setSelectedIndex(0);
            Project project = (Project) projectsModel.get(0);
            
            loadTasks(project.getId());
        }
    }
    
    private void loadProjects() {
        List<Project> projects = projectController.getAll();
          
        projectsModel.clear();
        
        for (int i = 0; i < projects.size(); i++) {
            Project project = projects.get(i);
            projectsModel.addElement(project);
        }
        
        ProjectList.setModel(projectsModel);
    }
    
    public void loadTasks(int projectId) {
        List<Task> tasks = taskController.getAll(projectId);
        tasksModel.setTasks(tasks);
        
        showTableTasks(!tasks.isEmpty());
    }
    
    public void showTableTasks(boolean hasTasks) {
        if (hasTasks) {
            if (EmptyTask.isVisible()) {
                EmptyTask.setVisible(false);
                TaskListPanel.remove(EmptyTask);
            }
            
            TaskListPanel.add(TableTasksScrool);
            TableTasksScrool.setVisible(true);
            TableTasksScrool.setSize(TaskListPanel.getWidth(), TaskListPanel.getHeight());
            
        } else {
            if (TableTasksScrool.isVisible()) {
                TableTasksScrool.setVisible(false);
                TaskListPanel.remove(TableTasksScrool);
            }
            
            TaskListPanel.add(EmptyTask);
            EmptyTask.setVisible(true);
            EmptyTask.setSize(TaskListPanel.getWidth(), TaskListPanel.getHeight());
            
        }
    }
}
